### ISSUE TITLE
Allow empty config files

### ISSUE THREAD

**Issue by xy2z** [xy2z/LiteConfig#7]
## Hacktoberfest 2021 PHP issue

Right now there's a bug if a config file is empty, when using `loadFile()` or `loadDir()` - it throws an exception like this:
```
PHP Fatal error:  Uncaught TypeError: xy2z\LiteConfig\LiteConfig::loadArray(): Argument #1 ($data) must be of type array, null given
```

Allow config files to be empty, with no returned data.

You can use this code to reproduce the bug. But first create 3 empty files in a config dir as seen below:
```php
<?php

require __DIR__ . '/src/LiteConfig.php';

use xy2z\LiteConfig\Liteconfig;

LiteConfig::loadFile(__DIR__ . '/config/empty.ini');
LiteConfig::loadFile(__DIR__ . '/config/empty.json');
LiteConfig::loadFile(__DIR__ . '/config/empty.php');
LiteConfig::loadDir(__DIR__ . '/config');

var_dump(LiteConfig::all());
```

Let me know if you have questions.

**Comment by OllieCrook** [comment]
I can take a look 👍🏼

**Comment by bstuff** [comment]
@xy2z please review
